config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :lists do
    resources :todos, only: [:create, :destroy]
  end

  namespace :api do
    resources :lists do
      resources :todos, only: [:create, :destroy]
    end    
  end

  root 'welcome#index'

  get 'welcome/about'

end

app/models/list.rb
class List < ActiveRecord::Base
	AVAIL_PERMISSIONS = ['open', 'viewable', 'private']
	DEFAULT_PERMISSION = 'private'
	
	has_many :todos, dependent: :destroy
	belongs_to :user
	validates :name, presence: true
	validates :user, presence: true
	validates :permissions, inclusion: {in: AVAIL_PERMISSIONS}

	def self.publicly_visible
		List.where("permissions IN ('open','viewable')")
	end

	def self.visible_to(u=nil)
		if u.nil?
			publicly_visible
		else
			List.where("permissions IN ('open','viewable') OR user_id = ?", u.id)
		end
	end

	def self.editable_by(u=nil)
		if u.nil?
			List.none
		else
			List.where("permissions = 'open' OR user_id = ?", u.id)
		end
	end

	def editable_by?(u=nil)
		u && (permissions == 'open' || user == u)
	end

	def visible_to?(u=nil)
		['open','viewable'].include?(permissions) || (u && (user == u))
	end
end

app/controllers/api/lists_controller.rb
class Api::ListsController < Api::ApiController  
	before_action :ensure_logged_in, only: [:create, :update, :destroy]
	before_action :set_list, only: [:update, :destroy, :show]

	def index
		lists = policy_scope(List)
		respond_with lists
	end

	def show
		respond_with @list
	end

	def create		
		@list = current_user.lists.new(list_params)
		authorize @list

		if @list.save
			respond_with @list
		else
			error :unprocessable_entity, @list.errors.full_messages
		end
	end

	def update
		if @list.update(list_params)
			respond_with @list
		else
			error :unprocessable_entity, @list.errors.full_messages
		end
	end

	def destroy
		if @list.destroy
			respond_with @list
		else
			error :unprocessable_entity, @list.errors.full_messages
		end
	end		

	private

	def set_list
		@list = policy_scope(List).find(params[:id])
		authorize @list
	end

	def list_params
		params.require(:list).permit(:name, :permissions)
	end	
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_list, only: [:edit, :update, :destroy, :show]
	respond_to :html
  helper_method :xeditable?

	def edit
	end

	def show
		@todo = Todo.new
	end

	def update
		if @list.update(list_params)
			flash[:notice] = 'Your list was updated'
			respond_with(@list) do |format|
				format.html { redirect_to @list }
			end
		else
			respond_with(@list) do |format|
				format.html { render 'edit' }
			end
		end
	end

	def create
		@list = current_user.lists.new(list_params)
		authorize @list		

		if @list.save
			@list_for_form = List.new
			flash[:notice] = 'Your new list was saved'
			respond_with(@list) do |format|
				format.html { redirect_to lists_path }
			end
		else
			@list_for_form = @list
			respond_with(@list) do |format|
				format.html { 
					@lists = current_user.lists #needed to render index (html)
					render 'index' 
				}
			end
		end
	end

	def destroy
		@list.destroy
				
		flash[:notice] = 'Your list was deleted'
		respond_with(@list) do |format|
			format.html { redirect_to lists_path }
		end
	end

	def index
		@list = List.new
		@lists = policy_scope(List).where(user: current_user)
	end
	
	def xeditable? object = nil
  	true
	end

	private

	def list_params
		params.require(:list).permit(:name, :permissions)
	end	

	def set_list
		@list = policy_scope(List).find(params[:id])
		authorize @list
	end
end

app/helpers/api/lists_helper.rb
module Api::ListsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for list, authenticity_token: true do |form| %>
	<div class="field form-group">
		<%= form.label :name %><br/>
		<%= form.text_field :name, placeholder: 'Name', autofocus: true %>
	</div>
	<div class="field form-group">
		<%= form.label :permissions %></br>	
		<%= form.select :permissions, List::AVAIL_PERMISSIONS %><br/>
	</div>
	<div class="field form-group">
		<%= form.submit 'Save', class: "btn btn-default", data: { create_list_button: true } %>
	</div>
<% end %>

app/views/lists/_lists_list.html.erb
<p id="no_lists_msg"<%= ' style="display: none;"'.html_safe if @lists.any? %>>There are no lists.</p>
<table class="table" id="lists_table" <%= ' style="display: none;"'.html_safe unless @lists.any? %>>
			<thead>
				<tr>
					<th>Name</th>
					<th>Permissions</th>
					<th></th>
				</tr>
			</thead>
			<%= render collection: lists, partial: 'lists_list_row', as: :list %>
</table>

app/views/lists/_lists_list_row.html.erb
<% unless list.new_record? %>
		<tr class='list-list-row' data-list-id='<%= list.id %>' id='list_<%= list.id %>'>
			<td><%= link_to list.name, list %></td>
			<td><%= list.permissions %></td>
			<td>
				<%= button_to(list, method: :delete, authenticity_token: true, id: "destroy_list_#{list.id}", data: { destroy_list_button: true }, class: "btn btn-danger") do %>
					<%= glyph(:trash) %>
				<% end %>
		</td>
		</tr>
<% end %>

app/views/lists/edit.html.erb
<h2>Edit List</h2>
<%= render 'shared/errors', obj: @list %>		
<%= render 'form', list: @list %>

app/views/lists/index.html.erb
<h2>My Lists</h2>
<%= render 'shared/errors', obj: @list %>		
<%= render 'lists_list', lists: @lists %>

<h2>New List</h2>
<%= render 'form', list: @list %>

app/views/lists/show.html.erb
<div id='editable_title'>
	<h2 class='list-name'><%= editable @list, :name, url: api_list_path(@list) %></h2>
	<%= editable @list, :permissions, type: :select, source: List::AVAIL_PERMISSIONS, class: 'permissions', url: api_list_path(@list) %>
	<noscript><%= link_to glyph(:pencil) + ' Edit', edit_list_path(@list), class: 'edit-link' %></noscript>

</div>

<%= render 'shared/errors', obj: @list %>		
<%= render 'todos/todos_list', todos: @list.todos %>
<%= render 'todos/form', todo: @todo %>